GET http://192.168.1.11:3001/api/notes
###
GET http://192.168.1.11:3001/api/notes/615836ce814e2409b672d661

###

POST http://192.168.1.11:3001/api/users
content-type: application/json

{
    "notes": [],
    "username": "root1",
    "name": "Superuser23",
    "password": "sekret1"
}

###

GET http://192.168.1.11:3001/api/users

###
POST http://192.168.1.11:3001/api/notes
content-type: application/json

{
    "content": "authentication test12",
    "important": true,
    "userId": "616068abf473d6a7db40c2ad"
}

###
POST http://192.168.1.11:3001/api/login
content-type: application/json

{
    "username": "root1",
    "password": "sekret1"
}

###
POST http://192.168.1.11:3001/api/notes
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QxIiwiaWQiOiI2MTYwNzIwZGI3ZjljMDJmOTUxZTc4MGYiLCJpYXQiOjE2MzM3MTA2MTh9.iA7glgsRnm-ZkRfd2RFPNBXP2_1zdXLV2hN7z-6x0A8

{
    "content": "authentication test1",
    "important": true
}

###
POST http://192.168.1.11:3001/api/notes
content-type: application/json

{
    "important1": true
}

###
DELETE http://192.168.1.11:3001/api/notes/615c687d38de8e9dcb3c8bf2

###
DELETE https://serene-brook-18625.herokuapp.com/api/notes/4