GET http://192.168.1.11:3001/api/notes
###
GET http://192.168.1.11:3001/api/notes/615836ce814e2409b672d661

###
POST http://192.168.1.11:3001/api/notes
content-type: application/json

{
    "content": "sample content through vs code rest plugin",
    "important": true
}

###
POST http://192.168.1.11:3002/api/notes
content-type: application/json

{
    "content123": "sample content through vs code rest plugin",
    "important1": true
}

###
DELETE http://192.168.1.11:3001/api/notes/615836ce814e2409b672d660

###
DELETE https://serene-brook-18625.herokuapp.com/api/notes/4